### ISSUE TITLE
tile_evenly with interval breaks when the amount of work is not evenly divisible by the number of workers

### ISSUE THREAD

**Issue by Dannnno** [agency-library/agency#341]
I'm using Agency for a school project, and I'm using the new `tile_evenly` with `interval` feature to help break up data. I was getting segfaults, and discovered that the last tile extends infinitely.

```c++
#include "agency/agency.hpp"
#include "agency/experimental.hpp"

int main() {
  const int num_workers = 7;
  const int upper_bound = 10;
  auto tiles = agency::experimental::tile_evenly(
      agency::experimental::interval(0, upper_bound), num_workers);

  for (int tile_id = 0; tile_id < num_workers; ++tile_id) {
      std::cout << "Tile id: " << tile_id << std::endl;
      for (auto index : tiles[tile_id]) {
          std::cout << " " << index << std::endl;
      }
  }
}
```

This yields the following output

```
Tile id: 0
 0
 1
Tile id: 1
 2
 3
Tile id: 2
 4
 5
Tile id: 3
 6
 7
Tile id: 4
 8
 9
Tile id: 5
Tile id: 6
 12
 13
 14
 15
 16
 17
 18
 19
```

It then continues infinitely.  We also reproduced this at `num_workers=32` and `upper_bound=60`.

#### Meta
------------
g++ version 6.2.0
Agency commit [520676d](https://github.com/agency-library/agency/commit/520676d1bf41e5bea9b13006c3d44e537d8094e4)
Flags: `g++ -std=c++11 -Iagency_dir example.cxx`

**Comment by jaredhoberock** [comment]
Hi Dan, thanks for the report.

`tile_evenly()` may return a different number of tiles than requested in corner cases such as the one you've discovered. In this particular case, there's no way to divide ten items into seven "evenly"-sized tiles. See also these issues: #338 & #339 

One way to guard against these cases is to iterate over the number of tiles returned, rather than the number of tiles requested:

```
#include "agency/agency.hpp"
#include "agency/experimental.hpp"

int main() {
  const int num_desired_tiles = 7;
  const int upper_bound = 10;
  auto tiles = agency::experimental::tile_evenly(
      agency::experimental::interval(0, upper_bound), num_desired_tiles);

  for (int tile_id = 0; tile_id < tiles.size(); ++tile_id) {
      std::cout << "Tile id: " << tile_id << std::endl;
      for (auto index : tiles[tile_id]) {
          std::cout << " " << index << std::endl;
      }
  }
}
```

If you want more control over the tile size (and therefore the number of created tiles), there's also `agency::experimental::tile(range, tile_size)`.

**Comment by Dannnno** [comment]
Yes, that makes sense, and fixed my issue. It does feel a little unintuitive that tile_evenly prioritizes making each tile equal in size rather than providing the number of tiles asked for, however now that I understand the behavior it makes sense.

Thank you for the help!
